---

- name: bash.d dir
  file:
    path: ~/.bash.d
    state: directory
  tags: always

- name: bashrc
  template:
    src: files/bash/bashrc.j2
    dest: "~/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  tags: always

- name: bash_profile
  template:
    src: files/bash/bash_profile.j2
    dest: "~/.bash_profile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  tags: always

- name: bash_local
  template:
    src: files/bash/bash_local.j2
    dest: "~/.bash_local"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  tags: always

- name: bash configs
  template:
    src: "{{ item }}"
    dest: "~/.bash.d/{{ item | basename | regex_replace('.j2','') }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_fileglob:
    - ./files/bash.d/*.j2
  tags: always
