#!/bin/sh
# Check for proper author names

error_msg() {
    echo "Please provide correct author information!"
    exit 1
}

if [ "${GIT_AUTHOR_NAME}" != "Morgan Humes" ]
then
    error_msg
fi
if [ "${GIT_AUTHOR_EMAIL}" != "morgan@lanaddict.com" ]
then
    error_msg
fi
