---

- name: gitignore
  template:
    src: files/git/gitignore.j2
    dest: ~/.gitignore
  tags: always

- name: gitconfig
  template:
    src: files/git/gitconfig.j2
    dest: ~/.gitconfig
  tags: always
