---

- name: Expect
  pacman:
    name: expect
  become: true
  tags: always

- name: AUR Builder - User Info
  shell: pinky -l aur_builder
  register: aur_builder_info
  changed_when: False
  tags: always

- name: AUR Builder - User
  user:
    name: aur_builder
    state: absent
  become: true
  when: '"/bin/nologin" not in aur_builder_info.stdout'
  tags: always

- name: AUR Builder - User
  user:
    name: aur_builder
    groups: wheel
    create_home: yes
    shell: /bin/nologin
    system: yes
    state: present
  become: true
  tags: always

- name: AUR Builder - Sudo
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: true
  tags: always
