---

- name: Expect
  pacman:
    name: expect
  become: true
  tags: always

- name: AUR Builder - User
  user:
    name: aur_builder
    group: wheel
  become: true
  tags: always

- name: AUR Builder - Sudo
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: true
  tags: always
