---

- name: GPG State
  shell: gpg --list-secret-keys
  register: gpg_secret_state
  changed_when: False
  tags: always

- name: Import GPG Secret Keys
  shell: "echo -e '{{ item.key }}' | gpg --import --batch -"
  no_log: True
  with_items: "{{ gpg_keys | filter_tags }}"
  when: item.id not in gpg_secret_state.stdout
  tags: always

- name: GPG Trusted State
  shell: gpg --export-ownertrust
  register: gpg_trusted_state
  changed_when: False
  tags: always

- name: Trust GPG Keys
  shell: |
    expect -c '
      spawn gpg --edit-key {{ item.id }} trust quit
      expect "Your decision? "
      send -- "5\r"
      expect "*ultimate trust?*"
      send -- "y\r"
      expect eof
    '
  no_log: True
  with_items: "{{ gpg_keys | filter_tags }}"
  when: item.id not in gpg_trusted_state.stdout
  tags: always
